* Solutions for SQL Practice book

Solutions for the book =SQL Practice Problems= by Sylvia Moestl Vasilik using literate programming with org mode.

* Getting started

** Setting up PostgreSQL

This repository uses a PostgreSQL container to solve and experiment with the problems in the book.

*** Install docker and docker-compose

- Follow the instructions in the official [[https://docs.docker.com/engine/install/ubuntu/][docker documentation.]]

*** Run the container

1. Get into the repository directory. Example

   #+begin_src sh
     cd ~/Documents/sql-practice-problems/
   #+end_src

2. Customize, add or delete the schema or data in the =init.sql= file.

3. Create and start the container.

#+begin_src sh
  docker-compose up
#+end_src


* Testing the solutions

1. Open the =solutions.org= inside of the introductory, intermediate or advanced directories.
2. M-C M-C in any of the code blocks containing SQL code.
3. The solution should match the one given in the book. TODO: Device a way to automatically compare the
   solution table given by the author against the one generated by the SQL solution.
